bug fix: boot_code may become 'NoneType' object
boot_code may cause an error as follows
  File "/home/jie/software/volatility-master/volatility/plugins/mbrparser.py", line 285, in calculate
    all_zeros = boot_code.count(chr(0)) == len(boot_code)
AttributeError: 'NoneType' object has no attribute 'count'